### ISSUE TITLE
Nil pointer issue around cluster creation

### ISSUE THREAD

**Issue by mhmxs** [linode/cluster-api-provider-linode#235]
## General:

* [X] Have you removed all sensitive information, including but not limited to access keys and passwords?
* [X] Have you checked to ensure there aren't other open or closed [Pull Requests](../../pulls) for the same bug/feature/question?

----

## Feature Requests:
* [ ] Have you explained your rationale for why this feature is needed? 
* [ ] Have you offered a proposed implementation/solution? 

----

## Bug Reporting

```golang
│ manager 2024-04-04T10:59:14Z    INFO    Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference    {"controller": "linodecluster", "co │
│ manager panic: runtime error: invalid memory address or nil pointer dereference [recovered]                                                                                     │
│ manager     panic: runtime error: invalid memory address or nil pointer dereference                                                                                             │
│ manager [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15d2d9a]                                                                                                 │
│ manager                                                                                                                                                                         │
│ manager goroutine 235 [running]:                                                                                                                                                │
│ manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()                                                                                  │
│ manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:116 +0x1e5                                                                 │
│ manager panic({0x1794a60?, 0x2973380?})                                                                                                                                         │
│ manager     /usr/local/go/src/runtime/panic.go:770 +0x132                                                                                                                       │
│ manager github.com/linode/cluster-api-provider-linode/controller.(*LinodeClusterReconciler).reconcileCreate(0xc0004fc2d0, {0x1c5ba18, 0xc000172690}, {{0x1c5fa38?, 0xc0006c83f0 │
│ manager     /workspace/controller/linodecluster_controller.go:172 +0x7a
```

### Expected Behavior

Create the cluster via manifests generated via 'make local-release`.

### Actual Behavior

The provider doesn't create cluster.

### Steps to Reproduce the Problem

  1. `clusterctl generate cluster test --infrastructure linode:0.0.0 --flavor clusterclass-kubeadm --config [config-by-docs]`
  1. Follow logs
  1.

#### Additional Notes

----

For general help or discussion, join the [Kubernetes Slack team](https://kubernetes.slack.com/messages/CD4B15LUR/details/) channel `#linode`. To sign up, use the [Kubernetes Slack inviter](http://slack.kubernetes.io/).

The [Linode Community](https://www.linode.com/community/questions/) is a great place to get additional support.

**Comment by mhmxs** [comment]
FYI: @eljohnson92

**Comment by mhmxs** [comment]
Has been solved at https://github.com/linode/cluster-api-provider-linode/commit/b16ad0543e250e41a0d3bfeba1cb7a6a87f6487f#diff-f7808f7ab8830ba93ef338e3409d5d92fdf4629b85cd8529c2ed1a7cec8a3253R173
